// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkc1_t7XoT38AurRag09iaucX6diqrZx4',
    appId: '1:765033539936:android:83131bfda2042f854b1605',
    messagingSenderId: '765033539936',
    projectId: 'coal-expert',
    storageBucket: 'coal-expert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtSOKnzCETQSTl9VO5JKF3_qhqiRdB5LI',
    appId: '1:765033539936:ios:8cd5cdfb42d1fb024b1605',
    messagingSenderId: '765033539936',
    projectId: 'coal-expert',
    storageBucket: 'coal-expert.appspot.com',
    iosClientId: '765033539936-ldqrabmajjb324vnv02094d9s8cn1iok.apps.googleusercontent.com',
    iosBundleId: 'com.coalexpert.app',
  );
}
